# Quarkus
quarkus.http.port=8080
quarkus.jackson.fail-on-unknown-properties=true

# DataSource ? PostgreSQL (ver local/docker-compose.yml)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bancada

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

#JWT
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=adacourse
quarkus.smallrye-jwt.enabled=true

# ==========================================
# CONFIGURAÇÕES ESPECÍFICAS DE TESTE (%test.)
# ==========================================

# 1. Define que nos testes o banco será o H2 em vez do Postgres
%test.quarkus.datasource.db-kind=h2

# 2. Configura a URL para rodar na memória RAM (banco limpo a cada execução)
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test_db

# 3. Diz ao Hibernate para criar e apagar as tabelas na memória a cada execução de teste
%test.quarkus.hibernate-orm.database.generation=drop-and-create


quarkus.jacoco.excludes=**/dto/**/*,**/models/**/*,**/enums/**/*