# Quarkus
quarkus.http.port=8080
quarkus.jackson.fail-on-unknown-properties=true

# DataSource ? PostgreSQL (ver local/docker-compose.yml)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bancada

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

#JWT
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=adacourse
quarkus.smallrye-jwt.enabled=true
